### ISSUE TITLE
dtype "float32"

### ISSUE THREAD

**Issue by VicencPB** [moganesyan/tensorflow_model_deployment#10]
Dear Mikheil,

thank you very much for this code; it really helps to understand how to use tensorflow serving, and it works very well.

I am trying to use it to access to a remote server, with a GPU RTX2080Ti, where Matterport Mask RCNN is running in a docker container, but I am experiencing long delays when using the GRPC call; it takes aprox. 10s to do the prediction

grpc_result = stub.Predict(request)

while it only takes 1s, when executing it on localhost.

Would it be possible to use uint8 types instead of float32, in order to send less data to the server?

Or can you recommend me another way to make it faster?

Thank you!

**Comment by moganesyan** [comment]
@VicencPB sorry for the delayed response. It seems like its a data problem and finding ways to cut down on the volume of data sent over the network is a correct intuition.

In theory sending uint8 instead of float32 is possible but it will require you to make modifications to the network and retrain it. At the moment the graph expects float inputs. I am not sure whether there is a way to force dtypes without modifying the network but even if there was a way, you'd likely see a performance degradation without retraining anyway...

Another potential thing you could do is base64 encode the input and send that instead. You'd need to modify the network by adding a decoding layer at the very top.

Hope that helps and do let me know if you find a solution.
