### ISSUE TITLE
base64 encoded images

### ISSUE THREAD

**Issue by jrash33** [moganesyan/tensorflow_model_deployment#8]
hey @moganesyan. So first off, this repo is the answer to all my problems. I have been searching online for over 2 weeks and your repo helped me more than you could ever know. It works perfectly! I wanted to ask if you had any versions that could accept base64 encoded images which is shown to be much faster (https://cloud.google.com/ai-platform/prediction/docs/online-predict?hl=en_US)
I've deployed the model onto gcp ai platform and the input json would look something like this:
```
{"image_bytes": {"b64": base64.b64encode(jpeg_data)}}
```
how difficult would this be to implement? THANK YOU

**Comment by moganesyan** [comment]
Hey man. Glad the repo helped you. 

I don't have a version with base64 encoded images. 
I think in order to implement it in a way deployable to AI platform, you'll (probably) have to add a B64 decode operation into the Mask R-CNN graph so that when you compile the model into TF-Serving, it persists. After that you can pass in the encoded image in a way that you specified above.

If you manage to get it done, please share the code!

hope this helped

**Comment by sreejith-ms** [comment]
@moganesyan any update on this?

> The repo will be expanded to include code for deploying and scaling the Mask RCNN on Google Cloud in the near future. So don't forget to check back in!!!
